### ISSUE TITLE
asserts still run after test has finished causing out of order TAP output

### ISSUE THREAD

**Issue by aghassemi** [ljharb/tape#110]
I am trying to implement a timeout mechanism where if a test does not finish in x time, my framework ends the test with a failed message. The issue I am running into is that after a test times-out and is ended, the previous asserts still run and produce out-of-order TAP output and plan != count errors ( or end() was called twice error if not using plan(x) )

Here is a simplified version of what I am doing:

```
var test = require('tape');

test('test one', function(t) {
  t.plan(1);
  setTimer(t);
  setTimeout(function() {
    t.pass('test one finished');
  }, 500);
});

test('test two', function(t) {
  t.plan(1);
  setTimer(t);
  setTimeout(function() {
    t.pass('test two finished');
  }, 100);
});

// end the test if not ended in 200 ms
function setTimer(t) {
  setTimeout(function() {
    console.log(t.ended);
    if (!t.ended) {
      t.end('Timedout :(');
    }
  }, 200);
}
```

The output I get back is

```
TAP version 13
# test one
undefined
not ok 1 Timedout :(
  ---
    operator: error
    expected: undefined
    actual:   'Timedout :('
  ...
# test two
ok 2 test two finished
true
ok 3 test one finished
not ok 4 plan != count
  ---
    operator: fail
    expected: 1
    actual:   2
  ...

1..4
# tests 4
# pass  2
# fail  2
```

which as you can see ran the test one assert even after the test had ended and reported the assert out-of-order after # test two. Also there is a random "undefined" line after #test one

Is there a better way to implement such timeout mechanism? Does it make sense for TAPE to build it in?

**Comment by mikesparr** [comment]
+1 on this. same issue with tape + supertest + sinon

**Comment by ljharb** [comment]
I don't think there's any way to fix this due to the nature of JS. The test ending has no ability to halt the execution of async-queued JS.
