### ISSUE TITLE
Not working on('data') event when passing objectMode:true

### ISSUE THREAD

**Issue by Josema** [ljharb/tape#247]
I'm trying to create my own colored reporter. But if I pass the objectMode:true does not print anything. I think is because is trying to get an string when actually is an Object. But then what is the sense of the objectMode:true ?

``` javascript
#!/usr/bin/env node
var tape = require('tape');
var through = require('through2');
var duplexer = require('duplexer');

//var tap = tape.createStream({ objectMode: true });  // Not working, can't receive and object
var tap = tape.createStream();                        // Working
var out = through();
var stream = duplexer(tap, out);

tap.on('data', function(data) {
    console.log(data.toString());
})

process.stdin
  .pipe(stream)
  .pipe(process.stdout);
process.on('exit', function() {
  if (stream.errors.length) process.exit(1);
})
```

Exists a way to get the object stringified on the data event?

**Comment by jbgrunewald** [comment]
Just call JSON.stringify(data)

**Comment by ljharb** [comment]
I'm not sure how to answer this question, and there's been no followup, so I'll close it.
