### ISSUE TITLE
Keep a changelog

### ISSUE THREAD

**Issue by aral** [ljharb/tape#517]
## Use case

Version 5.0.0 is a semver major update with breaking changes but I don’t know where to look for those breaking changes. A changelog would be the first place I’d normally look.

https://keepachangelog.com/en/1.0.0/

## Workaround

Do a search in the issues for people reporting breaking changes: https://github.com/substack/tape/issues?q=is%3Aissue+breaking

**Comment by aral** [comment]
OK, found them: https://github.com/substack/tape/releases/tag/v5.0.0

Not sure if I looked at a different tag previously. Closing since you already have a comparable system in place.

**Comment by Raynos** [comment]
Having breaking changes in a specific markdown file in the repo that we update for every major is beneficial.

The full changelog can stay in git releases.

I like a `MIGRATION.md` ( https://github.com/optoolco/tonic/blob/master/MIGRATION.md ) where instead of listing breaking changes you document how to migrate and "upgrade/fix" your old code for each breaking change.

**Comment by ljharb** [comment]
I’m very much in favor of a CHANGELOG.md file; i haven’t yet found a tool that can autogenerate this repo’s precious releases, including backports, properly, and the effort to manually create it is prohibitive. In the meantime, GitHub’s “releases” feature, and specifically, every tag, has release notes for that tag.

For tape, migrating is generally pretty straightforward - that doc would pretty much just contain tips about loose vs strict, and so forth.

**Comment by r0mflip** [comment]
Is querying GitHub API for all the releases/tags and using the response to build a [`HISTORY.md`](https://github.com/expressjs/express/blob/master/History.md) style file prohibitive?

**Comment by ljharb** [comment]
@r0mflip point me to a package that does that, and i'll use it :-)

**Comment by r0mflip** [comment]
It might exist in an alternate universe but in ours, we probably have yet to create it 😛

**Comment by r0mflip** [comment]
@ljharb So, I made one https://github.com/r0mflip/logtag

**Comment by customcommander** [comment]
@ljharb In case it helps I use [semantic-release](https://semantic-release.gitbook.io/semantic-release/):

> semantic-release uses the commit messages to determine the type of changes in the codebase. Following formalized conventions for commit messages, semantic-release automatically determines the next semantic version number, generates a changelog and publishes the release.

It cuts GitHub releases and publishes to NPM automatically by default. For automatic CHANGELOG generation, you need a plugin. It ticks all the boxes for me, not sure about yours though ;) Sharing in case it helps (note: I'm not in anyway related to that project!)

**Comment by ljharb** [comment]
@customcommander that doesn’t help for a number of reasons; automatic releasing is dangerous and I’ll never permit that; and the commit convention messages aren’t customizable and i find the term “chore” to be toxic.
