### ISSUE TITLE
Looking for a tap reporter

### ISSUE THREAD

**Issue by avin-kavish** [ljharb/tape#578]
I'm looking for a tap reporter that will give me output similar to ava. I.e. it concatanetes all the test names into one long string and displays either a green tick or cross next to it.

**Comment by ljharb** [comment]
Can you share a screenshot? I'm not sure what ava outputs.

**Comment by avin-kavish** [comment]
![image](https://user-images.githubusercontent.com/48435155/176003251-a4a081bf-e612-47d4-8db6-b40df0d5b5a0.png)
