### ISSUE TITLE
Suggestion: Ignore pattern directly instead of pointing to a file?

### ISSUE THREAD

**Issue by ppati000** [ljharb/tape#586]
The `--ignore` flag does not take a glob pattern, but a path to a file that contains the ignored patterns. This level of indirection is not always needed. For example, I'd love to have a simple command that runs all `*.test.ts` files except for files in a specific directory (e.g., a directory that contains end-to-end tests).

@ljharb what do you think about adding an `--ignorePattern` or similar option that takes a glob pattern? Would be willing to raise a PR :)

**Comment by ljharb** [comment]
That does seem reasonable - basically, shorthand for a one-line ignore file.

**Comment by ljharb** [comment]
Note, that we'd have to be very very explicit about how `--ignore` and `--ignorePattern` worked together - either they're mutually exclusive, or ignorePattern is concatenated to `--ignore`'s contents, or the reverse.

**Comment by ppati000** [comment]
@ljharb awesome, just opened https://github.com/ljharb/tape/pull/587. See the description there! :)
