### ISSUE TITLE
Tips on how to run a single test

### ISSUE THREAD

**Issue by naftalimurgor** [ljharb/tape#589]
## Summary
Scenario:
1. Let say we have several tests, hypothetically inside `test/`
2. Inside the `test/` directory we only want to focus on only running `foo.test.ts` from the terminal/commandline, 

How do we achieve this? , I can't seem to find any insights in the documentation.

Thanks

**Comment by ljharb** [comment]
You can run a single test *file* using tape by merely invoking it with node, or with tape. There isn’t an easy way of running s single *test*, though, besides `only`.

**Comment by naftalimurgor** [comment]
@ljharb 

Thanks! Pretty much answers the question.
