### ISSUE TITLE
looseEquals() from v4 failed in v5

### ISSUE THREAD

**Issue by m-holstein** [ljharb/tape#600]
My test from v4 with looseEquals failed in v5 and I have no idea why.
`  fixture req, (err, responses) ->
    t.looseEquals (responses.map (r) -> r.recipient),
      (_.reverse req.data.recipients),
      'info for every recipient'
    t.end()`

Data is:
`    data:
      recipients: [
        'foo@example.com'
        'bar@example.com'
        'baz@example.com'
      ]`

Is the behavior of looseEquals in v5 different?

**Comment by ljharb** [comment]
Yes, in v5 looseEqual is `==`, in v4 it's `.deepLooseEqual`. Change all of your `looseEquals` to `deepLooseEqual` and it should work in both majors.
